import React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import Tooltip from '@mui/material/Tooltip';
import EditIcon from '@mui/icons-material/Edit';
import DeleteIcon from '@mui/icons-material/Delete';
import TerminalIcon from '@mui/icons-material/Terminal';
import DescriptionIcon from '@mui/icons-material/Description';
import DownloadIcon from '@mui/icons-material/Download';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import { useClaudeTokens } from '@/shared/styles/ThemeContext';
import type { Skill, RegistrySkillDetail } from '@/shared/backend-bridge/apps/skills';
import { SkillPreviewData } from './SkillBuilderChat';
import { Selection } from './skillsTypes';
import ContentPreview from './ContentPreview';

interface SkillDetailPanelProps {
  selection: Selection;
  builderPreview: SkillPreviewData | null;
  selectedReg: RegistrySkillDetail | null;
  regDetailLoading: boolean;
  selectedLocal: Skill | null;
  contentView: 'preview' | 'raw';
  onContentViewChange: (view: 'preview' | 'raw') => void;
  onInstall: () => void;
  onEditInstall: () => void;
  onEdit: (skill: Skill) => void;
  onDelete: (id: string) => void;
}

const SkillDetailPanel: React.FC<SkillDetailPanelProps> = ({
  selection, builderPreview, selectedReg, regDetailLoading,
  selectedLocal, contentView, onContentViewChange,
  onInstall, onEditInstall, onEdit, onDelete,
}) => {
  const c = useClaudeTokens();

  return (
    <Box sx={{ flex: 1, height: '100%', display: 'flex', flexDirection: 'column', overflow: 'hidden', bgcolor: 'transparent' }}>
      {selection?.type === 'builder-preview' && builderPreview ? (
        <Box sx={{ p: 4, pb: 3, maxWidth: 1100, display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 0.5, flexShrink: 0 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
              <Typography sx={{ fontSize: '1.4rem', fontWeight: 700, color: c.text.primary, fontFamily: c.font.sans }}>
                {builderPreview.name || 'Untitled Skill'}
              </Typography>
              <Chip
                label="AI Preview"
                size="small"
                sx={{
                  bgcolor: `${c.accent.primary}15`,
                  color: c.accent.primary,
                  fontWeight: 600,
                  fontSize: '0.68rem',
                  height: 22,
                }}
              />
            </Box>
          </Box>

          {builderPreview.command && (
            <Box sx={{ mb: 1.5, flexShrink: 0 }}>
              <Chip
                icon={<TerminalIcon sx={{ fontSize: 14 }} />}
                label={`/${builderPreview.command}`}
                size="small"
                sx={{
                  bgcolor: 'rgba(174,86,48,0.08)', color: c.accent.primary,
                  fontWeight: 500, fontSize: '0.78rem', height: 26,
                }}
              />
            </Box>
          )}

          <Box sx={{ mb: 1, flexShrink: 0 }}>
            <Typography sx={{ fontSize: '0.78rem', color: c.text.ghost }}>
              Generated by <strong style={{ color: c.accent.primary, fontWeight: 600 }}>Skill Builder</strong>
            </Typography>
          </Box>

          {builderPreview.description && (
            <Box sx={{ mb: 2, flexShrink: 0 }}>
              <Typography sx={{ fontSize: '0.78rem', color: c.text.ghost, mb: 0.5 }}>Description</Typography>
              <Typography sx={{ fontSize: '0.88rem', color: c.text.secondary, lineHeight: 1.6 }}>
                {builderPreview.description}
              </Typography>
            </Box>
          )}

          <ContentPreview content={builderPreview.content} contentView={contentView} onContentViewChange={onContentViewChange} />
        </Box>
      ) : !selection ? (
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: c.text.ghost, gap: 2 }}>
          <DescriptionIcon sx={{ fontSize: 48, opacity: 0.3 }} />
          <Typography sx={{ fontSize: '0.9rem' }}>Select a skill to view its details</Typography>
        </Box>
      ) : selection.type === 'registry' ? (
        regDetailLoading && !selectedReg ? (
          <Box sx={{ display: 'flex', justifyContent: 'center', pt: 12 }}>
            <CircularProgress size={24} sx={{ color: c.accent.primary }} />
          </Box>
        ) : selectedReg ? (
          <Box sx={{ p: 4, pb: 3, maxWidth: 1100, display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 0.5, flexShrink: 0 }}>
              <Typography sx={{ fontSize: '1.4rem', fontWeight: 700, color: c.text.primary, fontFamily: c.font.sans }}>
                {selectedReg.name}
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                <Button
                  variant="contained"
                  size="small"
                  startIcon={<DownloadIcon sx={{ fontSize: 15 }} />}
                  onClick={onInstall}
                  sx={{
                    bgcolor: c.accent.primary, '&:hover': { bgcolor: c.accent.pressed },
                    textTransform: 'none', borderRadius: `${c.radius.md}px`, px: 2, py: 0.5,
                    fontSize: '0.8rem', fontWeight: 600, boxShadow: 'none',
                  }}
                >
                  Install
                </Button>
                <Button
                  variant="outlined"
                  size="small"
                  startIcon={<EditIcon sx={{ fontSize: 15 }} />}
                  onClick={onEditInstall}
                  sx={{
                    borderColor: c.border.strong, color: c.text.secondary,
                    '&:hover': { borderColor: c.accent.primary, color: c.accent.primary, bgcolor: 'rgba(174,86,48,0.04)' },
                    textTransform: 'none', borderRadius: `${c.radius.md}px`, px: 2, py: 0.5,
                    fontSize: '0.8rem', fontWeight: 600,
                  }}
                >
                  Edit & Install
                </Button>
                {selectedReg.repositoryUrl && (
                  <Tooltip title="View on GitHub">
                    <IconButton
                      size="small"
                      component="a"
                      href={selectedReg.repositoryUrl}
                      sx={{ color: c.text.tertiary, '&:hover': { color: c.text.primary } }}
                    >
                      <OpenInNewIcon sx={{ fontSize: 18 }} />
                    </IconButton>
                  </Tooltip>
                )}
              </Box>
            </Box>

            <Box sx={{ mb: 1, flexShrink: 0 }}>
              <Typography sx={{ fontSize: '0.78rem', color: c.text.ghost }}>Added by <strong style={{ color: c.text.secondary, fontWeight: 600 }}>Anthropic</strong></Typography>
            </Box>

            <Box sx={{ mb: 2, flexShrink: 0 }}>
              <Typography sx={{ fontSize: '0.78rem', color: c.text.ghost, mb: 0.5 }}>Description</Typography>
              <Typography sx={{ fontSize: '0.88rem', color: c.text.secondary, lineHeight: 1.6 }}>
                {selectedReg.description}
              </Typography>
            </Box>

            <ContentPreview content={selectedReg.content} contentView={contentView} onContentViewChange={onContentViewChange} />
          </Box>
        ) : null
      ) : selectedLocal ? (
        <Box sx={{ p: 4, pb: 3, maxWidth: 1100, display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 0.5, flexShrink: 0 }}>
            <Typography sx={{ fontSize: '1.4rem', fontWeight: 700, color: c.text.primary, fontFamily: c.font.sans }}>
              {selectedLocal.name}
            </Typography>
            <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center' }}>
              <Tooltip title="Edit">
                <IconButton size="small" onClick={() => onEdit(selectedLocal)} sx={{ color: c.text.tertiary, '&:hover': { color: c.accent.primary } }}>
                  <EditIcon sx={{ fontSize: 18 }} />
                </IconButton>
              </Tooltip>
              <Tooltip title="Delete">
                <IconButton size="small" onClick={() => onDelete(selectedLocal.id)} sx={{ color: c.text.tertiary, '&:hover': { color: c.status.error } }}>
                  <DeleteIcon sx={{ fontSize: 18 }} />
                </IconButton>
              </Tooltip>
            </Box>
          </Box>

          {selectedLocal.command && (
            <Box sx={{ mb: 1.5, flexShrink: 0 }}>
              <Chip
                icon={<TerminalIcon sx={{ fontSize: 14 }} />}
                label={`/${selectedLocal.command}`}
                size="small"
                sx={{
                  bgcolor: 'rgba(174,86,48,0.08)', color: c.accent.primary,
                  fontWeight: 500, fontSize: '0.78rem', height: 26,
                }}
              />
            </Box>
          )}

          <Box sx={{ mb: 1, flexShrink: 0 }}>
            <Typography sx={{ fontSize: '0.78rem', color: c.text.ghost }}>Added by <strong style={{ color: c.text.secondary, fontWeight: 600 }}>You</strong></Typography>
          </Box>

          {selectedLocal.description && (
            <Box sx={{ mb: 2, flexShrink: 0 }}>
              <Typography sx={{ fontSize: '0.78rem', color: c.text.ghost, mb: 0.5 }}>Description</Typography>
              <Typography sx={{ fontSize: '0.88rem', color: c.text.secondary, lineHeight: 1.6 }}>
                {selectedLocal.description}
              </Typography>
            </Box>
          )}

          <ContentPreview content={selectedLocal.content} contentView={contentView} onContentViewChange={onContentViewChange} />
        </Box>
      ) : null}
    </Box>
  );
};

export default SkillDetailPanel;
